version: '3.3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: afus
      POSTGRES_USER: afus
      POSTGRES_PASSWORD: afus
    ports:
      - 5432:5432
    restart: always