name: Docker CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version number
        id: version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: ./server

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/afus:latest, ${{ secrets.DOCKERHUB_USERNAME }}/afus:${{ steps.version.outputs.current-version }}
          platforms: linux/amd64,linux/arm64

  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get npm version
        id: version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: ./server
      
      - name: Tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
          CUSTOM_TAG: v${{ steps.version.outputs.current-version }}