name: Tests

on: 
  pull_request:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: Start postgres
        run: docker compose -f docker-compose.dev.yml up -d
      
      - name: Install dependencies
        working-directory: ./server
        run: npm ci
      
      - name: Run unit tests
        working-directory: ./server
        run: npm run test
      
      - name: Run e2e tests
        working-directory: ./server
        run: npm run test:e2e

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Test docker build
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64